# Generated by Django 4.2.16 on 2024-10-26 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do cadastro')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField()),
                ('porcentagem', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agencia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa_cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('aberto', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa_dinheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('aberto', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao_mesa_dinheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% rendimento')),
                ('rend_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor rendimento')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('reinvestimento', models.BooleanField(default=False)),
                ('aporte', models.BooleanField(default=False)),
                ('saque', models.BooleanField(default=False)),
                ('transferencia', models.BooleanField(default=False)),
                ('mesa_dinheiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mesa_dinheiro')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao_mesa_cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% rendimento')),
                ('rend_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor rendimento')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('reinvestimento', models.BooleanField(default=False)),
                ('aporte', models.BooleanField(default=False)),
                ('saque', models.BooleanField(default=False)),
                ('transferencia', models.BooleanField(default=False)),
                ('mesa_cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mesa_cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.socio'),
        ),
    ]
