# Generated by Django 4.2.16 on 2024-10-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao_mesa_cartao',
            name='quantidade_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao_mesa_cartao',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor da Parcela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacao_mesa_cartao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cartão'),
        ),
    ]
