# Generated by Django 4.2.16 on 2024-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transacao_mesa_cartao_quantidade_parcelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao_mesa_cartao',
            name='valor_cartao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Cartão'),
        ),
        migrations.AlterField(
            model_name='transacao_mesa_cartao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Investido'),
        ),
    ]
