# Generated by Django 4.2.16 on 2024-10-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transacao_mesa_cartao_valor_cartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao_mesa_cartao',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transacao_mesa_cartao',
            name='valor_cartao',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Cartão'),
        ),
    ]
