# Generated by Django 4.2.16 on 2024-10-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transacao_mesa_cartao_concluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao_mesa_cartao',
            name='data_primeira_parcela',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao_mesa_cartao',
            name='data_ultima_parcela',
            field=models.DateField(blank=True, null=True),
        ),
    ]
