# Generated by Django 4.2.16 on 2024-10-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transacao_mesa_cartao_data_primeira_parcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao_mesa_cartao',
            name='data_primeira_parcela',
            field=models.DateField(blank=True, null=True, verbose_name='Data da primeira parcela'),
        ),
        migrations.AlterField(
            model_name='transacao_mesa_cartao',
            name='data_ultima_parcela',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última parcela'),
        ),
    ]
