# Generated by Django 4.2.16 on 2024-10-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transacao_mesa_cartao_data_primeira_parcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao_mesa_cartao',
            name='valor_cartao',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Maquineta'),
        ),
    ]
