# Generated by Django 4.2.16 on 2024-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transacao_mesa_cartao_valor_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='data_criaca',
            field=models.DateField(blank=True, null=True, verbose_name='Data da criação'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='gerente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
