# Generated by Django 4.2.16 on 2024-10-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agencia_cnpj_agencia_data_criaca_agencia_endereco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencia',
            old_name='data_criaca',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='agencia',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
    ]
