# Generated by Django 4.2.16 on 2024-11-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transacao_mesa_cartao_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao_mesa_dinheiro',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
