# Generated by Django 4.2.16 on 2024-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transacao_mesa_dinheiro_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao_mesa_dinheiro',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave pix'),
        ),
    ]
