# Generated by Django 4.2.16 on 2024-11-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transacao_mesa_dinheiro_pix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pix_agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('banco', models.CharField(max_length=255)),
                ('chave', models.CharField(max_length=255)),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agencia')),
            ],
        ),
    ]
