# Generated by Django 4.2.16 on 2024-11-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pix_agencia_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix_agencia',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
