# Generated by Django 4.2.16 on 2024-11-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_transacao_mesa_dinheiro_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao_mesa_dinheiro',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave pix'),
        ),
    ]
