# Generated by Django 4.2.16 on 2024-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_transacao_mesa_dinheiro_pix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao_mesa_dinheiro',
            name='chave_pix',
        ),
        migrations.AddField(
            model_name='transacao_mesa_dinheiro',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave pix'),
        ),
    ]
