# Generated by Django 4.2.16 on 2024-11-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_transacao_mesa_dinheiro_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao_mesa_dinheiro',
            name='chave_pix_saque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
