# Generated by Django 4.2.16 on 2024-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_transacao_mesa_dinheiro_banco_pix_saque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao_mesa_dinheiro',
            name='banco_pix_saque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco pix saque'),
        ),
        migrations.AlterField(
            model_name='transacao_mesa_dinheiro',
            name='chave_pix_saque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave pix saque'),
        ),
        migrations.AlterField(
            model_name='transacao_mesa_dinheiro',
            name='nome_pix_saque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular pix saque'),
        ),
    ]
