# Generated by Django 4.2.16 on 2024-11-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_transacao_mesa_dinheiro_banco_pix_saque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento_cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Investido')),
                ('valor_maquineta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Maquineta')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% rendimento')),
                ('rend_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor rendimento')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('pix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave pix')),
                ('concluido', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes-prestacao/')),
                ('pago', models.BooleanField(default=False)),
                ('atraso', models.BooleanField(default=False)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investimento_cartao')),
            ],
        ),
    ]
