# Generated by Django 4.2.16 on 2024-11-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_investimento_cartao_prestacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento_cartao',
            name='pix',
        ),
    ]
