# Generated by Django 4.2.16 on 2024-11-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_saque_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento_cartao',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim'),
        ),
    ]
