# Generated by Django 4.2.16 on 2024-11-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_investimento_cartao_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao_mesa_dinheiro',
            name='data_inicio',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='Rendimento_cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investimento_cartao')),
            ],
        ),
    ]
