# Generated by Django 4.2.16 on 2024-11-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_rendimento_cartao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao_mesa_alavancagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data')),
                ('data_fim', models.DateField()),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% rendimento')),
                ('rend_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor rendimento')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('chave_pix_saque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave pix saque')),
                ('nome_pix_saque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular pix saque')),
                ('banco_pix_saque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco pix saque')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('reinvestimento', models.BooleanField(default=False)),
                ('aporte', models.BooleanField(default=False)),
                ('saque', models.BooleanField(default=False)),
                ('transferencia', models.BooleanField(default=False)),
                ('chave_pix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pix_agencia', verbose_name='Chave Pix')),
                ('mesa_dinheiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mesa_dinheiro')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa_alavancagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('aberto', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
            ],
        ),
    ]
