# Generated by Django 4.2.16 on 2024-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_transacao_mesa_alavancagem_chave_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa_dinheiro',
            name='alavancagem',
            field=models.BooleanField(default=False),
        ),
    ]
