# Generated by Django 4.2.16 on 2024-12-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_mesa_dinheiro_alavancagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='% rendimento')),
                ('cartao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('ativo', models.BooleanField(default=True)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investimento')),
            ],
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(blank=True, null=True)),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes-prestacao/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='investimento_cartao',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='mesa_dinheiro',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='saque_cartao',
            name='investimento',
        ),
        migrations.RemoveField(
            model_name='transacao_mesa_cartao',
            name='mesa_cartao',
        ),
        migrations.RemoveField(
            model_name='transacao_mesa_dinheiro',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='transacao_mesa_dinheiro',
            name='mesa_dinheiro',
        ),
        migrations.RemoveField(
            model_name='prestacao',
            name='atraso',
        ),
        migrations.RemoveField(
            model_name='prestacao',
            name='comprovante',
        ),
        migrations.RemoveField(
            model_name='prestacao',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='prestacao',
            name='data_vencimento',
        ),
        migrations.AddField(
            model_name='prestacao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='pago',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.DeleteModel(
            name='Mesa_cartao',
        ),
        migrations.DeleteModel(
            name='Mesa_dinheiro',
        ),
        migrations.DeleteModel(
            name='Saque_cartao',
        ),
        migrations.DeleteModel(
            name='Transacao_mesa_cartao',
        ),
        migrations.DeleteModel(
            name='Transacao_mesa_dinheiro',
        ),
        migrations.AddField(
            model_name='investimento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipo_investimento'),
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='investimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investimento'),
        ),
        migrations.DeleteModel(
            name='Investimento_cartao',
        ),
    ]
