# Generated by Django 4.2.16 on 2024-12-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_investimento_rendimento_retirada_tipo_investimento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestacao',
        ),
    ]
