# Generated by Django 4.2.16 on 2024-12-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_delete_prestacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento_cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data fim')),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Investido')),
                ('valor_maquineta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Maquineta')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% rendimento')),
                ('rend_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor rendimento')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('concluido', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa_cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('aberto', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa_dinheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('aberto', models.BooleanField(default=True)),
                ('alavancagem', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes-prestacao/')),
                ('pago', models.BooleanField(default=False)),
                ('atraso', models.BooleanField(default=False)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investimento_cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Saque_cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes-prestacao/')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investimento_cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao_mesa_cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_primeira_parcela', models.DateField(blank=True, null=True, verbose_name='Data da primeira parcela')),
                ('data_ultima_parcela', models.DateField(blank=True, null=True, verbose_name='Data da última parcela')),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('quantidade_parcelas', models.IntegerField(blank=True, null=True)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Investido')),
                ('valor_cartao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Maquineta')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% rendimento')),
                ('rend_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor rendimento')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('pix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave pix')),
                ('reinvestimento', models.BooleanField(default=False)),
                ('aporte', models.BooleanField(default=False)),
                ('saque', models.BooleanField(default=False)),
                ('transferencia', models.BooleanField(default=False)),
                ('concluido', models.BooleanField(default=False)),
                ('mesa_cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mesa_cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao_mesa_dinheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data')),
                ('data_fim', models.DateField()),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% rendimento')),
                ('rend_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor rendimento')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo final')),
                ('chave_pix_saque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave pix saque')),
                ('nome_pix_saque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular pix saque')),
                ('banco_pix_saque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco pix saque')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('reinvestimento', models.BooleanField(default=False)),
                ('aporte', models.BooleanField(default=False)),
                ('saque', models.BooleanField(default=False)),
                ('transferencia', models.BooleanField(default=False)),
                ('chave_pix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pix_agencia', verbose_name='Chave Pix')),
                ('mesa_dinheiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mesa_dinheiro')),
            ],
        ),
        migrations.RemoveField(
            model_name='rendimento',
            name='investimento',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='socio',
        ),
        migrations.DeleteModel(
            name='Investimento',
        ),
        migrations.DeleteModel(
            name='Rendimento',
        ),
        migrations.DeleteModel(
            name='Retirada',
        ),
        migrations.DeleteModel(
            name='Tipo_investimento',
        ),
    ]
