# Generated by Django 4.2.16 on 2024-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_investimento_rendimento_retirada_tipo_investimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='alavancagem',
            field=models.BooleanField(default=False),
        ),
    ]
