# Generated by Django 4.2.16 on 2024-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_investimento_alavancagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='ativo',
        ),
        migrations.AddField(
            model_name='investimento',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investimento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
