# Generated by Django 4.2.16 on 2024-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_investimento_ativo_investimento_autorizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='dinheiro',
            field=models.BooleanField(default=True),
        ),
    ]
