# Generated by Django 4.2.16 on 2024-12-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_investimento_dinheiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo_investimento',
        ),
    ]
