# Generated by Django 4.2.16 on 2024-12-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_investimento_tipo_delete_tipo_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='valor_maquineta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Maquineta'),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
    ]
