# Generated by Django 4.2.16 on 2024-12-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_investimento_valor_maquineta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='valor_maquineta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Valor Maquineta'),
        ),
    ]
