# Generated by Django 4.2.16 on 2024-12-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_investimento_valor_maquineta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='valor_maquineta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor Maquineta'),
        ),
    ]
