# Generated by Django 4.2.16 on 2024-12-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_investimento_valor_maquineta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirada',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('pago', models.BooleanField(default=True)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investimento')),
            ],
        ),
    ]
