# Generated by Django 4.2.16 on 2024-12-17 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0049_superusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirada',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retirada',
            name='aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retirada',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
