# Generated by Django 4.2.16 on 2024-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_retirada_aprovado_retirada_aprovador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='reinvestido',
            field=models.BooleanField(default=False),
        ),
    ]
