# Generated by Django 4.2.16 on 2024-12-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_retirada_banco_pix_retirada_chave_pix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes-investimentos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
        ),
    ]
