# Generated by Django 4.2.16 on 2024-12-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_solicitacaoinvestimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
    ]
