# Generated by Django 4.2.16 on 2024-12-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_investimento_retirado_rendimento_retirado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimento',
            name='reinvestido',
            field=models.BooleanField(default=False),
        ),
    ]
