# Generated by Django 4.2.16 on 2024-12-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_rendimento_reinvestido'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='marcado_reinvestir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investimento',
            name='marcado_retirar',
            field=models.BooleanField(default=False),
        ),
    ]
