# Generated by Django 4.2.16 on 2024-12-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_investimento_marcado_reinvestir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimento',
            name='marcado_reinvestir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='marcado_retirar',
            field=models.BooleanField(default=False),
        ),
    ]
