# Generated by Django 4.2.16 on 2024-12-29 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0057_rendimento_marcado_reinvestir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='autorizador_investimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizador_investimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investimento',
            name='autorizador_reinvestimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizador_reinvestimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investimento',
            name='autorizador_retirada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizador_retirada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investimento',
            name='comprovante_investimento',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes-solicitacoes/'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='data_solicitacao_investimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de solicitação do investimento'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='data_solicitacao_reinvestimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de solicitação do reinvestimento'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='data_solicitacao_retirada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de solicitação do reinvestimento'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='investimento_solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investimento',
            name='reinvestimento_solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investimento',
            name='retirada_solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendimento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
