# Generated by Django 4.2.16 on 2024-12-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_investimento_autorizador_investimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='comprovante_retirada',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes-retiradas/'),
        ),
    ]
