# Generated by Django 4.2.16 on 2024-12-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_investimento_comprovante_retirada'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='banco_pix_retirada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='chave_pix_retirada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave pix'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='titular_pix_retirada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titular'),
        ),
    ]
