# Generated by Django 4.2.16 on 2024-12-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_investimento_banco_pix_retirada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='autorizador_investimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='autorizador_reinvestimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='autorizador_retirada',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='banco_pix_retirada',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='chave_pix_retirada',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='comprovante_investimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='comprovante_retirada',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='data_solicitacao_investimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='data_solicitacao_reinvestimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='data_solicitacao_retirada',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='investimento_solicitado',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='reinvestimento_solicitado',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='retirada_solicitado',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='titular_pix_retirada',
        ),
    ]
