# Generated by Django 4.2.16 on 2025-01-04 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0062_investimento_autorizador_investimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('aberto', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='rendimento',
            name='investimento',
        ),
        migrations.RemoveField(
            model_name='solicitacaoinvestimento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='autorizador_investimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='autorizador_reinvestimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='autorizador_retirada',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='cartao',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='comprovante_investimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='comprovante_retirada',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='data_solicitacao_investimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='data_solicitacao_reinvestimento',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='data_solicitacao_retirada',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='finalizado',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='investimento_solicitado',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='marcado_reinvestir',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='marcado_retirar',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='reinvestimento_solicitado',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='retirada_solicitado',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='retirado',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='valor_maquineta',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='aprovador',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='data_retirada',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='finalizado',
        ),
        migrations.RemoveField(
            model_name='retirada',
            name='socio',
        ),
        migrations.AddField(
            model_name='investimento',
            name='autorizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investimento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes-investimentos/'),
        ),
        migrations.AddField(
            model_name='investimento',
            name='data_solicitacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investimento',
            name='valor_rendimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor Rendimento'),
        ),
        migrations.AddField(
            model_name='retirada',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retirada',
            name='autorizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retirada',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Prestacao',
        ),
        migrations.DeleteModel(
            name='Rendimento',
        ),
        migrations.DeleteModel(
            name='SolicitacaoInvestimento',
        ),
        migrations.AddField(
            model_name='investimento',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.periodo'),
        ),
        migrations.AddField(
            model_name='retirada',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.periodo'),
        ),
    ]
