# Generated by Django 4.2.16 on 2025-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_periodo_remove_rendimento_investimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='alavancagem',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='dinheiro',
        ),
        migrations.AddField(
            model_name='periodo',
            name='alavancagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodo',
            name='dinheiro',
            field=models.BooleanField(default=True),
        ),
    ]
