# Generated by Django 4.2.16 on 2025-01-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0064_remove_investimento_alavancagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestimentoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data fim')),
                ('valor_maquineta', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor maquineta')),
                ('valor_real', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor')),
                ('rendimento_total', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Rendimento total')),
                ('rendimento_mes', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Rendimento mês')),
                ('porcent_rend_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='% rendimento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes-investimentos/')),
                ('autorizado', models.BooleanField(default=False)),
                ('aberto', models.BooleanField(default=True)),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.socio')),
            ],
        ),
        migrations.CreateModel(
            name='PrestacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor')),
                ('autorizado', models.BooleanField(default=False)),
                ('pago', models.BooleanField(default=True)),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizador_prestacao', to=settings.AUTH_USER_MODEL)),
                ('confirmador_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmador_pagamento_prestacao', to=settings.AUTH_USER_MODEL)),
                ('investinmento_cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investimentocartao')),
            ],
        ),
    ]
