# Generated by Django 4.2.16 on 2025-01-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_investimentocartao_prestacaocartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimentocartao',
            name='autorizado',
            field=models.BooleanField(default=True),
        ),
    ]
