# Generated by Django 4.2.16 on 2025-01-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_investimentocartao_valor_prestacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimentocartao',
            name='num_prestacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investimentocartao',
            name='valor_real',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor Investido'),
        ),
    ]
