# Generated by Django 4.2.16 on 2025-01-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_investimentocartao_num_prestacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaocartao',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
