# Generated by Django 4.2.16 on 2025-01-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_retirada_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirada',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.periodo'),
        ),
    ]
