# Generated by Django 4.2.16 on 2025-01-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_retirada_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocartao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data pagamento'),
        ),
    ]
