# Generated by Django 4.2.16 on 2025-01-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_prestacaocartao_data_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestacaocartao',
            old_name='investinmento_cartao',
            new_name='investimento_cartao',
        ),
        migrations.AlterField(
            model_name='prestacaocartao',
            name='data',
            field=models.DateField(verbose_name='Data vencimento'),
        ),
    ]
