# Generated by Django 4.2.16 on 2025-01-05 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0073_rename_investinmento_cartao_prestacaocartao_investimento_cartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocartao',
            name='cancelador_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelador_pagamento_prestacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
